before_script:
  - apt-get update -y
  - apt-get install -y libssl-dev build-essential wget
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  - source /root/.bashrc
  - nvm install node
  - nvm use node
  - npm install @codelenny/module-server-examples --registry http://makerchip.com:4873
  - npm install

test:
  script:
    - npm run-script extensive-test
