git:
  submodules: false
language: node_js
node_js:
  - "node"
  - "6"
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - npm install
script:
  - npm run-script extensive-test
