language: node_js
node_js:
  - "node"
  - "6"
install:
  - npm install @codelenny/module-server-examples --registry http://makerchip.com:4873
  - npm install
script:
  - npm run-script extensive-test
